apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: set-in-overlay
      http:
        paths:
          - path: /fieldlab
            pathType: ImplementationSpecific
            backend:
              service:
                name: keda-interceptor-alias
                port:
                  number: 8080
  tls:
    - hosts:
        - set-in-overlay
      secretName: imx-tls
